using System.ComponentModel.DataAnnotations.Schema;

namespace CardGames.War.Api.Entities
{
    /// <summary>
    /// Represents a single game into the database.
    /// </summary>
    [Table("Game")]
    public class Game
    {
        /// <summary>
        /// Game ID. (autogenerated.
        /// </summary>
        public int Id { get; set; }

#pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        /// <summary>
        /// User who plays the game.
        /// </summary>
        public string UserEmail { get; set; }

        /// <summary>
        /// Says wich user won the game.
        /// </summary>
        public string? Winner { get; set; }

     
#pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.

        /// <summary>
        /// When the game was created/started.
        /// </summary>
        public DateTime StartDate { get; set; }

        /// <summary>
        /// When the game was finished.
        /// </summary>
        public DateTime? FinishDate { get; set; }
       
    }
}
